### ISSUE TITLE
detail information for missing element linting rules is not visible

### ISSUE THREAD

**Issue by FO-e-X** [camunda/camunda-modeler-linter-plugin#11]
Hi,

we found an error with handling linting errors for missing elements. I.e. 
https://github.com/bpmn-io/bpmnlint/tree/master/docs/rules -> bpmnlint/docs/rules/start-event-required.md 

The situation is, that we have 2 participants in a model. The first one is a simple process with a StartEvent. The second one has a LaneSet and no StartEvent in any lane. Yes, this is an error. The BPMNLinter-Plugin counts this error, but the red X is missing. Thats why the detail information of the error is missing too. The only information is "1 Errors". It took a while to get the details, by adding a breakpoint in the script where the errors are counted.
The example in the docs show this red X, but the process is not placed in a LaneSet.

Maybe you could change the handling of errors a bit. For example add the details to the counter, maybe only if it depends on a missing element. Placing the details at the first element in the process could be a bit hard to realise, because you have to "know" what element is the first... :)

Best regards
Frank

**Comment by MaxTru** [comment]
Thanks for reporting!

With #16, this situation would appear like this: 
![Screenshot_20210415_160927](https://user-images.githubusercontent.com/42800119/114883266-0b819980-9e05-11eb-88d7-7edefb0b285c.png)

I assume this solves what you describe?

Thanks for a quick check and confirmation.

**Comment by nikku** [comment]
@MaxTru A more appropriate solution could be to display process related errors on the participant that represents the process, visually.

**Comment by nikku** [comment]
Closing this issue again, as the we display the errors now, at least.

We may follow up with further improvements via https://github.com/bpmn-io/bpmn-js-bpmnlint/issues/30.
