### ISSUE TITLE
bpmnlintrc file load error

### ISSUE THREAD

**Issue by sekharne** [camunda/camunda-modeler-linter-plugin#25]
Hi,
@nikku ; @pinussilvestrus  and team

I tried the approach stated for adding the linter plugin as stated, but i am facing module loading issue, 
![modeler issue](https://user-images.githubusercontent.com/84576136/163152408-643b1a90-8778-471f-95c9-792d5d738d8f.png)

I added below rules also still facing the issue,
![tsconfig](https://user-images.githubusercontent.com/84576136/163152708-3da74c6f-2089-488f-aa15-7abb84cda50b.png)

Requesting your inputs in integrating bpmn linter to the camunda modeler angular version

**Comment by MaxTru** [comment]
Thanks for reaching out.

* Could you please use our bug issue template? This will allow to better understand and reproduce the error
* If this is a general question, please head over to forum.bpmn.io
* Please reference context (e.g., you stated `I tried the approach stated for adding the linter plugin as stated`)
