### ISSUE TITLE
Deprecate Plugin

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler-linter-plugin#29]
* [x] deprecate repository (https://github.com/camunda/camunda-modeler-linter-plugin/commit/f2ef1223bb0f466541662850be1aeb5638da4236, https://github.com/camunda/camunda-modeler-linter-plugin/commit/e9ab068d3af1d8321e381bfceaecf53b6d168bf9)
* [ ] update plugin to indicate deprecation when used
* [ ] document migration to Camunda Modeler 5.3 plus custom lint rules

---

Related to https://github.com/camunda/camunda-modeler-linter-plugin/issues/28

**Comment by philippfromme** [comment]
There are two ways we could handle compatibility with specific Camunda Modeler versions:

### 1. Imperative - Plugin is in control

The Camunda Modeler would expose its version and the plugin would check for compatibility. This would involve
* https://github.com/camunda/camunda-modeler/compare/app-version 
* https://github.com/camunda/camunda-modeler-plugin-helpers/compare/compatibility.

### 2. Declarative - Camunda Modeler is in control

This has been sketched in https://github.com/camunda/camunda-modeler/issues/1043. Plugins would declare their compatibility and the Camunda Modeler would check for compatibility.

@nikku @camunda/modeling-dev Your thoughts?

**Comment by nikku** [comment]
My proposal is that we await further feedback before doing advanced deprecation action here.

As of now it seems like the existing communication is enough; we do have relevant issues in all repositories, and our built-in debugging steps allow users to root-cause the issue (https://github.com/camunda/camunda-modeler/issues/3234).

----

I personally like what you sketched https://github.com/camunda/camunda-modeler-linter-plugin/issues/29#issuecomment-1262764353, option :one:.

If you have capacity to pursue this route (create PRs, double check plug-in helper documentation, ...) that would be awesome. Note though that we still miss an "plug-in outdated" notification from within the app for a working end-to-end story.

**Comment by philippfromme** [comment]
Okay, I'll unassign myself for now.

**Comment by philippfromme** [comment]
We'll continue with https://github.com/camunda/camunda-modeler/issues/3239.
