### ISSUE TITLE
lint does not work with modeler 5.5

### ISSUE THREAD

**Issue by damnmso** [camunda/camunda-modeler-linter-plugin#30]
I created a little bpmn and noticed, that the lint does not show any error, where an error is obvious.
so i created a little bpmn that makes absolutely no sense and is wrong (syntax), no error is shown

![image](https://user-images.githubusercontent.com/117813624/200784466-3df8e5a3-2ddb-4c90-abb2-558cf70b8774.png)

I would have expected some errors shown below. But it says "No errors."

**Comment by nikku** [comment]
Please use our existing issue template and file all relevant details.

**Comment by nikku** [comment]
If you're in a rush you can [roll you're own rules plug-in](https://github.com/camunda/camunda-modeler-custom-linter-rules-plugin) already.
