### ISSUE TITLE
Expressions shown as class instead

### ISSUE THREAD

**Issue by vikkee57** [camunda/camunda-modeler-linter-plugin#40]
Not sure what's a good repo to post this issue, there are few bpmnlint projects over here, but I observed something that seems like a bug and thought of sharing. 

When working on the lint plugin and validating service tasks, I see that the expression property is appearing as class.

You have a service task with implementation type as "expression" 
<img width="684" alt="image" src="https://github.com/camunda/camunda-modeler-linter-plugin/assets/584225/9dde5ecb-934b-4f22-b359-eb79edb89e13">

But when you try to read this property and debug, it is stored against node.class field? 
<img width="712" alt="image" src="https://github.com/camunda/camunda-modeler-linter-plugin/assets/584225/f6ece2c8-17f8-4aec-b4bd-f36bccef0ea7">

**Comment by nikku** [comment]
@vikkee57 I'm a little bit confused what your observation has to do with linting? I'd assume you'll observe the same without it. 

If you can reproduce your issue in the [Camunda Modeler](https://github.com/camunda/camunda-modeler) could you create a bug report there, with _clear steps to reproduce_ and _expected behavior_? Find below a quick test I conducted myself by the context you provided:

![capture q7TI1l_optimized](https://github.com/camunda/camunda-modeler-linter-plugin/assets/58601/6284a787-b064-4728-a6d4-bdf9fa840984)


If you have questions on our tooling then [the Community Forum](https://forum.camunda.io/) may be the right place to answer these.

**Comment by vikkee57** [comment]
Thanks a lot for taking a look at my thread @nikku!

Yes no problems with the modeler so far, it is captured correctly. But I suspect there is a possible bug in the lint plugin here?  
If you see my second screenshot from IDE, it does not have a equivalent node.expression property. It instead stores the expression against node.class.

So if anyone wanted to write a new lint rule on something related to camunda:expression, we can't?!

**Comment by nikku** [comment]
@vikkee57 I'm not sure if you added a breakpoint with a cached result or what is going on. Without _clear_ steps to reproduce we'll not be able to follow up on your report.

Using an end-to-end test I reproduced that there is no bug in the modeler itself.

**Comment by vikkee57** [comment]
Appreciate you checking this @nikku, I am probably then missing something in my own implementation. I will submit a different issue if I find anything substantial.
