### ISSUE TITLE
Sequence flow leaving merging exclusive gateway should not require an expression

### ISSUE THREAD

**Issue by rob2universe** [camunda/camunda-modeler-linter-plugin#7]
A sequence flow leaving a merging exclusive gateway does not require an condition.
(Issue does not exist for merging parallel gateway)

Error disappears if 
      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression" />
Is added by selecting "Expression" in sequence flow properties, but not providing one.

![image](https://user-images.githubusercontent.com/1978908/75875202-3782cb00-5e4e-11ea-914c-2b52ae0a030d.png)

**Comment by nikku** [comment]
Thanks for reporting this bug.

Fixed with [`bpmnlint-plugin-camunda@0.4.1`](https://github.com/camunda/bpmnlint-plugin-camunda/blob/master/CHANGELOG.md#041).
